In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

In [3]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

# Read the CSV and Perform Basic Data Cleaning

In [4]:
# https://help.lendingclub.com/hc/en-us/articles/215488038-What-do-the-different-Note-statuses-mean-

columns = [
    "loan_amnt", "int_rate", "installment", "home_ownership",
    "annual_inc", "verification_status", "issue_d", "loan_status",
    "pymnt_plan", "dti", "delinq_2yrs", "inq_last_6mths",
    "open_acc", "pub_rec", "revol_bal", "total_acc",
    "initial_list_status", "out_prncp", "out_prncp_inv", "total_pymnt",
    "total_pymnt_inv", "total_rec_prncp", "total_rec_int", "total_rec_late_fee",
    "recoveries", "collection_recovery_fee", "last_pymnt_amnt", "next_pymnt_d",
    "collections_12_mths_ex_med", "policy_code", "application_type", "acc_now_delinq",
    "tot_coll_amt", "tot_cur_bal", "open_acc_6m", "open_act_il",
    "open_il_12m", "open_il_24m", "mths_since_rcnt_il", "total_bal_il",
    "il_util", "open_rv_12m", "open_rv_24m", "max_bal_bc",
    "all_util", "total_rev_hi_lim", "inq_fi", "total_cu_tl",
    "inq_last_12m", "acc_open_past_24mths", "avg_cur_bal", "bc_open_to_buy",
    "bc_util", "chargeoff_within_12_mths", "delinq_amnt", "mo_sin_old_il_acct",
    "mo_sin_old_rev_tl_op", "mo_sin_rcnt_rev_tl_op", "mo_sin_rcnt_tl", "mort_acc",
    "mths_since_recent_bc", "mths_since_recent_inq", "num_accts_ever_120_pd", "num_actv_bc_tl",
    "num_actv_rev_tl", "num_bc_sats", "num_bc_tl", "num_il_tl",
    "num_op_rev_tl", "num_rev_accts", "num_rev_tl_bal_gt_0",
    "num_sats", "num_tl_120dpd_2m", "num_tl_30dpd", "num_tl_90g_dpd_24m",
    "num_tl_op_past_12m", "pct_tl_nvr_dlq", "percent_bc_gt_75", "pub_rec_bankruptcies",
    "tax_liens", "tot_hi_cred_lim", "total_bal_ex_mort", "total_bc_limit",
    "total_il_high_credit_limit", "hardship_flag", "debt_settlement_flag"
]

target = ["loan_status"]

In [5]:
# Load the data
file_path = Path('/Users/Hammad/Desktop/Data Analytics Class/Credit_Risk_Analysis/Resources/LoanStats_2019Q1.csv')
df = pd.read_csv(file_path, skiprows=1)[:-2]
df = df.loc[:, columns].copy()

# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')

# Drop the null rows
df = df.dropna()

# Remove the `Issued` loan status
issued_mask = df['loan_status'] != 'Issued'
df = df.loc[issued_mask]

# convert interest rate to numerical
df['int_rate'] = df['int_rate'].str.replace('%', '')
df['int_rate'] = df['int_rate'].astype('float') / 100


# Convert the target column values to low_risk and high_risk based on their values
x = {'Current': 'low_risk'}   
df = df.replace(x)

x = dict.fromkeys(['Late (31-120 days)', 'Late (16-30 days)', 'Default', 'In Grace Period'], 'high_risk')    
df = df.replace(x)

df.reset_index(inplace=True, drop=True)

df.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,dti,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,10500.0,0.1719,375.35,RENT,66000.0,Source Verified,Mar-2019,low_risk,n,27.24,...,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0,N,N
1,25000.0,0.2000,929.09,MORTGAGE,105000.0,Verified,Mar-2019,low_risk,n,20.23,...,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0,N,N
2,20000.0,0.2000,529.88,MORTGAGE,56000.0,Verified,Mar-2019,low_risk,n,24.26,...,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0,N,N
3,10000.0,0.1640,353.55,RENT,92000.0,Verified,Mar-2019,low_risk,n,31.44,...,100.0,50.0,1.0,0.0,99506.0,68784.0,19700.0,76506.0,N,N
4,22000.0,0.1474,520.39,MORTGAGE,52000.0,Not Verified,Mar-2019,low_risk,n,18.76,...,100.0,0.0,0.0,0.0,219750.0,25919.0,27600.0,20000.0,N,N

# Split the Data into Training and Testing

In [6]:
# string values conversion from numerical values
df2 = df.copy()

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df2['home_ownership'] = le.fit_transform(df2['home_ownership']) 
df2['verification_status'] = le.fit_transform(df2['verification_status'])
df2['loan_status'] = le.fit_transform(df2['loan_status'])
df2['pymnt_plan'] = le.fit_transform(df2['pymnt_plan'])
df2['initial_list_status'] = le.fit_transform(df2['initial_list_status'])
df2['pymnt_plan'] = le.fit_transform(df2['pymnt_plan'])
df2['application_type'] = le.fit_transform(df2['application_type'])
df2['hardship_flag'] = le.fit_transform(df2['hardship_flag'])
df2['debt_settlement_flag'] = le.fit_transform(df2['debt_settlement_flag'])
df2['issue_d'] = le.fit_transform(df2['issue_d'])
df2['next_pymnt_d'] = le.fit_transform(df2['next_pymnt_d'])

df2.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,dti,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,10500.0,0.1719,375.35,3,66000.0,1,2,1,0,27.24,...,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0,0,0
1,25000.0,0.2000,929.09,1,105000.0,2,2,1,0,20.23,...,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0,0,0
2,20000.0,0.2000,529.88,1,56000.0,2,2,1,0,24.26,...,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0,0,0
3,10000.0,0.1640,353.55,3,92000.0,2,2,1,0,31.44,...,100.0,50.0,1.0,0.0,99506.0,68784.0,19700.0,76506.0,0,0
4,22000.0,0.1474,520.39,1,52000.0,0,2,1,0,18.76,...,100.0,0.0,0.0,0.0,219750.0,25919.0,27600.0,20000.0,0,0

In [7]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68817 entries, 0 to 68816
Data columns (total 86 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   loan_amnt                   68817 non-null  float64
 1   int_rate                    68817 non-null  float64
 2   installment                 68817 non-null  float64
 3   home_ownership              68817 non-null  int32
 4   annual_inc                  68817 non-null  float64
 5   verification_status         68817 non-null  int32
 6   issue_d                     68817 non-null  int32
 7   loan_status                 68817 non-null  int32
 8   pymnt_plan                  68817 non-null  int64
 9   dti                         68817 non-null  float64
 10  delinq_2yrs                 68817 non-null  float64
 11  inq_last_6mths              68817 non-null  float64
 12  open_acc                    68817 non-null  float64
 13  pub_rec                     68817 non-null  float64
 14  revol_bal                   68817 non-null  float64
 15  total_acc                   68817 non-null  float64
 16  initial_list_status         68817 non-null  int32
 17  out_prncp                   68817 non-null  float64
 18  out_prncp_inv               68817 non-null  float64
 19  total_pymnt                 68817 non-null  float64
 20  total_pymnt_inv             68817 non-null  float64
 21  total_rec_prncp             68817 non-null  float64
 22  total_rec_int               68817 non-null  float64
 23  total_rec_late_fee          68817 non-null  float64
 24  recoveries                  68817 non-null  float64
 25  collection_recovery_fee     68817 non-null  float64
 26  last_pymnt_amnt             68817 non-null  float64
 27  next_pymnt_d                68817 non-null  int32
 28  collections_12_mths_ex_med  68817 non-null  float64
 29  policy_code                 68817 non-null  float64
 30  application_type            68817 non-null  int32
 31  acc_now_delinq              68817 non-null  float64
 32  tot_coll_amt                68817 non-null  float64
 33  tot_cur_bal                 68817 non-null  float64
 34  open_acc_6m                 68817 non-null  float64
 35  open_act_il                 68817 non-null  float64
 36  open_il_12m                 68817 non-null  float64
 37  open_il_24m                 68817 non-null  float64
 38  mths_since_rcnt_il          68817 non-null  float64
 39  total_bal_il                68817 non-null  float64
 40  il_util                     68817 non-null  float64
 41  open_rv_12m                 68817 non-null  float64
 42  open_rv_24m                 68817 non-null  float64
 43  max_bal_bc                  68817 non-null  float64
 44  all_util                    68817 non-null  float64
 45  total_rev_hi_lim            68817 non-null  float64
 46  inq_fi                      68817 non-null  float64
 47  total_cu_tl                 68817 non-null  float64
 48  inq_last_12m                68817 non-null  float64
 49  acc_open_past_24mths        68817 non-null  float64
 50  avg_cur_bal                 68817 non-null  float64
 51  bc_open_to_buy              68817 non-null  float64
 52  bc_util                     68817 non-null  float64
 53  chargeoff_within_12_mths    68817 non-null  float64
 54  delinq_amnt                 68817 non-null  float64
 55  mo_sin_old_il_acct          68817 non-null  float64
 56  mo_sin_old_rev_tl_op        68817 non-null  float64
 57  mo_sin_rcnt_rev_tl_op       68817 non-null  float64
 58  mo_sin_rcnt_tl              68817 non-null  float64
 59  mort_acc                    68817 non-null  float64
 60  mths_since_recent_bc        68817 non-null  float64
 61  mths_since_recent_inq       68817 non-null  float64
 62  num_accts_ever_120_pd       68817 non-null  float64
 63  num_actv_bc_tl              68817 non-null  float64
 64  num_actv_rev_tl             68817 non-null  float64
 65  num_bc_sats                 68817 non-null  float64
 66  num_bc_tl                   68817 non-null  float64
 67  num_il_tl                   68817 non-null  float64
 68  num_op_rev_tl               68817 non-null  float64
 69  num_rev_accts               68817 non-null  float64
 70  num_rev_tl_bal_gt_0         68817 non-null  float64
 71  num_sats                    68817 non-null  float64
 72  num_tl_120dpd_2m            68817 non-null  float64
 73  num_tl_30dpd                68817 non-null  float64
 74  num_tl_90g_dpd_24m          68817 non-null  float64
 75  num_tl_op_past_12m          68817 non-null  float64
 76  pct_tl_nvr_dlq              68817 non-null  float64
 77  percent_bc_gt_75            68817 non-null  float64
 78  pub_rec_bankruptcies        68817 non-null  float64
 79  tax_liens                   68817 non-null  float64
 80  tot_hi_cred_lim             68817 non-null  float64
 81  total_bal_ex_mort           68817 non-null  float64
 82  total_bc_limit              68817 non-null  float64
 83  total_il_high_credit_limit  68817 non-null  float64
 84  hardship_flag               68817 non-null  int32
 85  debt_settlement_flag        68817 non-null  int32
dtypes: float64(76), int32(9), int64(1)
memory usage: 42.8 MB

In [8]:
# Create our features
X = df2.copy()
X = X.drop("loan_status", axis=1)

# Create our target
y = df2["loan_status"]

In [9]:
X.describe()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,issue_d,pymnt_plan,dti,delinq_2yrs,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
count,68817.000000,68817.000000,68817.000000,68817.000000,6.881700e+04,68817.000000,68817.000000,68817.0,68817.000000,68817.000000,...,68817.000000,68817.000000,68817.000000,68817.0,6.881700e+04,6.881700e+04,68817.000000,6.881700e+04,68817.0,68817.0
mean,16677.594562,0.127718,480.652863,1.812779,8.821371e+04,0.669994,0.805542,0.0,21.778153,0.217766,...,95.057627,30.626217,0.125972,0.0,2.100332e+05,6.133843e+04,29734.128558,5.572240e+04,0.0,0.0
std,10277.348590,0.048130,288.062432,0.941313,1.155800e+05,0.719105,0.714932,0.0,20.199244,0.718367,...,8.326426,33.631463,0.336732,0.0,1.928088e+05,5.738798e+04,26795.394232,5.095845e+04,0.0,0.0
min,1000.000000,0.060000,30.890000,0.000000,4.000000e+01,0.000000,0.000000,0.0,0.000000,0.000000,...,20.000000,0.000000,0.000000,0.0,3.600000e+03,2.350000e+02,100.000000,1.270000e+02,0.0,0.0
25%,9000.000000,0.088100,265.730000,1.000000,5.000000e+04,0.000000,0.000000,0.0,13.890000,0.000000,...,93.000000,0.000000,0.000000,0.0,6.697700e+04,2.650300e+04,11600.000000,2.288000e+04,0.0,0.0
50%,15000.000000,0.118000,404.560000,1.000000,7.300000e+04,1.000000,1.000000,0.0,19.760000,0.000000,...,100.000000,20.000000,0.000000,0.0,1.467100e+05,4.535700e+04,22100.000000,4.200000e+04,0.0,0.0
75%,24000.000000,0.155700,648.100000,3.000000,1.040000e+05,1.000000,1.000000,0.0,26.660000,0.000000,...,100.000000,50.000000,0.000000,0.0,3.036400e+05,7.657000e+04,39300.000000,7.249900e+04,0.0,0.0
max,40000.000000,0.308400,1676.230000,3.000000,8.797500e+06,2.000000,2.000000,0.0,999.000000,18.000000,...,100.000000,100.000000,4.000000,0.0,3.292782e+06,1.295455e+06,509400.000000,1.426964e+06,0.0,0.0

In [10]:
# Check the balance of our target values
# y['loan_status'].value_counts()
y.value_counts()

1    68470
0      347
Name: loan_status, dtype: int64

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
                                                    X, y, 
                                                    random_state=78, train_size=0.75)

In [12]:
# print model results
print(Counter(y_train))
print(Counter(y_test))

Counter({1: 51357, 0: 255})
Counter({1: 17113, 0: 92})

# Ensemble Learners

In this section, you will compare two ensemble algorithms to determine which algorithm results in the best performance. You will train a Balanced Random Forest Classifier and an Easy Ensemble AdaBoost classifier . For each algorithm, be sure to complete the folliowing steps:

1. Train the model using the training data. 
2. Calculate the balanced accuracy score from sklearn.metrics.
3. Print the confusion matrix from sklearn.metrics.
4. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.
5. For the Balanced Random Forest Classifier onely, print the feature importance sorted in descending order (most important feature to least important) along with the feature score

Note: Use a random state of 1 for each algorithm to ensure consistency between tests

### Balanced Random Forest Classifier

In [ ]:
pip install -U imbalanced-learn

In [13]:
# Resample the training data with the BalancedRandomForestClassifier
from imblearn.ensemble import BalancedRandomForestClassifier

brfc = BalancedRandomForestClassifier(n_estimators=100, random_state=1)

#model fit
brfc.fit(X_train, y_train)

BalancedRandomForestClassifier(random_state=1)

In [ ]:
# define brf model
brf_model = brf_model.fit(X_train, y_train)

In [14]:
# Calculated the balanced accuracy score
y_pred = brfc.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.7519613870970201

In [15]:
# Display the confusion matrix
cm = confusion_matrix(y_test, y_pred)

# DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual high_risk", "Actual low_risk"], columns=["Predicted high_risk", "Predicted low_risk"])
cm_df

                  Predicted high_risk  Predicted low_risk
Actual high_risk                   58                  34
Actual low_risk                  2165               14948

In [16]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.03      0.63      0.87      0.05      0.74      0.54        92
          1       1.00      0.87      0.63      0.93      0.74      0.56     17113

avg / total       0.99      0.87      0.63      0.93      0.74      0.56     17205

In [17]:
# List the features sorted in descending order by feature importance
features_rank = sorted(zip(brfc.feature_importances_, X.columns), reverse=True)
for feature in features_rank:
    print(f"{feature[1]}: ({feature[0]})")

total_rec_prncp: (0.07972578916270898)
last_pymnt_amnt: (0.07184199283761979)
total_pymnt: (0.06428200815827503)
total_pymnt_inv: (0.05361500880138094)
total_rec_int: (0.04397653617040098)
int_rate: (0.03372491650210961)
issue_d: (0.0261889114749861)
mths_since_recent_inq: (0.019458020914104493)
mo_sin_old_rev_tl_op: (0.019412889680972666)
dti: (0.017719802114217368)
bc_open_to_buy: (0.016511806392147194)
out_prncp: (0.016230999521916263)
annual_inc: (0.015727577793596847)
revol_bal: (0.015518209726778413)
installment: (0.01537638021631967)
il_util: (0.01534576834053173)
bc_util: (0.01524337492856352)
all_util: (0.014804822806011017)
mo_sin_old_il_acct: (0.014168797191308665)
total_bal_ex_mort: (0.013807745211418582)
max_bal_bc: (0.013706135412067779)
out_prncp_inv: (0.013600058476436798)
total_bc_limit: (0.013370828968501867)
tot_cur_bal: (0.013291160492260465)
num_rev_accts: (0.013167436261829158)
total_il_high_credit_limit: (0.012991564970961942)
total_bal_il: (0.012886857397571847)
tot_hi_cred_lim: (0.012751204802486375)
avg_cur_bal: (0.012695565836212019)
loan_amnt: (0.012149586217267756)
total_rev_hi_lim: (0.011972292960109014)
num_il_tl: (0.01169396964465183)
mths_since_rcnt_il: (0.011480169944538756)
mo_sin_rcnt_tl: (0.010834030409385626)
num_bc_tl: (0.010636923441491407)
pct_tl_nvr_dlq: (0.009902990454331361)
num_op_rev_tl: (0.009583797472923776)
num_rev_tl_bal_gt_0: (0.00954400711736832)
num_sats: (0.009531541491378788)
acc_open_past_24mths: (0.00949893599107308)
num_bc_sats: (0.009459495458884717)
mths_since_recent_bc: (0.009310812455242755)
inq_last_6mths: (0.009196356753732612)
open_acc: (0.008933887221564567)
inq_last_12m: (0.00893297352596123)
total_acc: (0.008659538077087879)
total_rec_late_fee: (0.008446585390432186)
num_actv_rev_tl: (0.008104198988427893)
mo_sin_rcnt_rev_tl_op: (0.008095192314711529)
num_actv_bc_tl: (0.0075140271408159764)
open_il_24m: (0.007455056300689601)
inq_fi: (0.007067372484502829)
percent_bc_gt_75: (0.006980005411277437)
mort_acc: (0.006838687537339177)
num_tl_op_past_12m: (0.006323261159358868)
open_act_il: (0.006012166780991702)
open_acc_6m: (0.0059709434419639)
verification_status: (0.0057786209923925465)
next_pymnt_d: (0.00518672772786083)
open_rv_12m: (0.0051855811664639545)
total_cu_tl: (0.005090117018630528)
open_rv_24m: (0.004769825883504664)
delinq_2yrs: (0.004264237094270189)
open_il_12m: (0.003671222981884013)
tot_coll_amt: (0.0035981972867186384)
num_accts_ever_120_pd: (0.002807351979682167)
home_ownership: (0.002694659532340319)
pub_rec_bankruptcies: (0.001916498659040448)
initial_list_status: (0.0014351424643750865)
application_type: (0.0008394167822006734)
pub_rec: (0.0008035190493497912)
num_tl_90g_dpd_24m: (0.00033775005811691617)
collections_12_mths_ex_med: (0.00020448794797292054)
chargeoff_within_12_mths: (0.0001456672239957641)
tax_liens: (0.0)
recoveries: (0.0)
pymnt_plan: (0.0)
policy_code: (0.0)
num_tl_30dpd: (0.0)
num_tl_120dpd_2m: (0.0)
hardship_flag: (0.0)
delinq_amnt: (0.0)
debt_settlement_flag: (0.0)
collection_recovery_fee: (0.0)
acc_now_delinq: (0.0)

### Easy Ensemble AdaBoost Classifier

In [18]:
# Train the EasyEnsembleClassifier
from imblearn.ensemble import EasyEnsembleClassifier

eec = EasyEnsembleClassifier(n_estimators=100, random_state=1)
eec

EasyEnsembleClassifier(n_estimators=100, random_state=1)

In [20]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
balanced_accuracy_score(y_test, y_pred)

0.7519613870970201

In [21]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred)

array([[   58,    34],
       [ 2165, 14948]], dtype=int64)

In [22]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.03      0.63      0.87      0.05      0.74      0.54        92
          1       1.00      0.87      0.63      0.93      0.74      0.56     17113

avg / total       0.99      0.87      0.63      0.93      0.74      0.56     17205